<?php

/**
 * Implementation of hook_views_api().
 */
function nice_dash_user_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'nice_dash_user'),
  );
}

/**
 * Implementation of hook_nice_dash_widgets()
 */
function nice_dash_user_nice_dash_widgets(){
	module_load_include('inc', 'nice_dash_user', 'nice_dash_user.widgets');

	$widgets['user_latest'] = array(
		'title' => t('Latest registered users'),
		'callback' => 'nice_dash_user_widget_latest',
		//'file' => 'nice_dash_content.widgets.inc'
	);

	$widgets['user_last_login'] = array(
		'title' => t('Latest loggedin users'),
		'callback' => 'nice_dash_user_widget_last_login',
		//'file' => 'nice_dash_content.widgets.inc'
	);

	return $widgets;
}