<?php

// Load in the API helpers
module_load_include('inc','nice_dash', 'nice_dash.api');

/**
 * Implementation of hook_menu
 */
function nice_dash_menu() {

 $items['admin/dashboard'] = array(
    'title' => 'Dashboard',
    'page callback' => 'nice_dash_dashboard_page',
    'access arguments' => array('view nice dashboard'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'nice_dash.pages.inc'
  );

 $items['admin/dashboard/view'] = array(
    'title' => 'View',
    'page callback' => 'nice_dash_dashboard_page',
    'access arguments' => array('view nice dashboard'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -1,
    'file' => 'nice_dash.pages.inc'
  );

  $items['admin/dashboard/configure'] = array(
    'title' => 'Configure',
    'page callback' => 'nice_dash_dashboard_overview_page',
    'access arguments' => array('administer nice dashboard'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'nice_dash.pages.inc'
  );

	$items['admin/dashboard/configure/overview'] = array(
    'title' => 'Overview',
    'page callback' => 'nice_dash_dashboard_overview_page',
    'access arguments' => array('administer nice dashboard'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
		'weight' => -1,
    'file' => 'nice_dash.pages.inc'
  );

	$items['admin/dashboard/configure/create-dashboard'] = array(
		'title' => 'Create dashboard',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nice_dash_dashboard_settings_form'),
		'access arguments' => array('administer nice dashboard'),
		'type' => MENU_LOCAL_TASK,
		'file' => 'nice_dash.pages.inc'
	);


	 $items['admin/dashboard/configure/%/delete'] = array(
		'title' => 'Create new dashboard',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nice_dash_dashboard_delete_form',3),
		'access arguments' => array('administer nice dashboard'),
		'type' => MENU_CALLBACK,
		'file' => 'nice_dash.pages.inc'
	);

	// Widgets

	$items['admin/dashboard/configure/create-widget'] = array(
		'title' => 'Create widget',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nice_dash_widget_settings_form'),
		'access arguments' => array('administer nice dashboard'),
		'type' => MENU_LOCAL_TASK,
		'file' => 'nice_dash.pages.inc'
	);

	$items['admin/dashboard/widget/%/delete'] = array(
		'title' => 'Delete widget',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nice_dash_widget_delete_form',3),
		'access arguments' => array('administer nice dashboard'),
		'type' => MENU_CALLBACK,
		'file' => 'nice_dash.pages.inc'
	);

	 $items['admin/dashboard/widget/%/edit'] = array(
		'title' => 'Edit widget',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nice_dash_widget_settings_form',3),
		'access arguments' => array('administer nice dashboard'),
		'type' => MENU_CALLBACK,
		'file' => 'nice_dash.pages.inc'
	);


 // Implement all the dashboard menu calls
 $dashboards = nice_dash_dashboards();

	if(count($dashboards) > 0){

	 $first = TRUE;

	 foreach($dashboards as $dashboard){
		 $items['admin/dashboard/configure/'.$dashboard['did'].'/edit'] = array(
		 'title' => 'Edit '.$dashboard['name'],
		 'page callback' => 'drupal_get_form',
		 'page arguments' => array('nice_dash_dashboard_settings_form',3),
		 'access arguments' => array('administer nice dashboard'),
		 'type' => MENU_LOCAL_TASK,
		 'file' => 'nice_dash.pages.inc'
		);

		if($first){
		 $type = MENU_DEFAULT_LOCAL_TASK;
		 $first = FALSE;
		}
		else {
		 $type = MENU_LOCAL_TASK;
		}

		$items['admin/dashboard/view/'.$dashboard['did']] = array(
		 'title' => $dashboard['name'],
		 'page callback' => 'nice_dash_dashboard_page',
		 'page arguments' => array(3),
		 'access arguments' => array('view nice dashboard'),
		 'type' => $type,
		 'weight' => $dashboard['weight'],
		 'file' => 'nice_dash.pages.inc'
		);
	 }
	}
  return $items;
}

/**
  *  Implementation of hook_init().
  */
function nice_dash_init() {
  if (isset($_SESSION['admin_dashboard_redirect'])) {
    unset($_SESSION['admin_dashboard_redirect']);
    drupal_goto('admin/dashboard');
  }
}

/**
 * Implementation of hook_user
 */
function nice_dash_user($op, &$edit, &$account, $category = NULL){
  switch ($op) {
    case 'login':
    if (user_access('view admindashboard')) {
      $_SESSION['admin_dashboard_redirect'] = true;
    }
    break;
  }
}

/**
 * Implementation of hook_perm
 */
function nice_dash_perm() {
  return array('administer nice dashboard','view nice dashboard');
}

/**
 * Implementation of hook_theme()
 */
function nice_dash_theme($existing, $type, $theme, $path){
  $path = drupal_get_path('module', 'nice_dash');

  return array(
    'nice_dash_component' => array(
      'arguments' => array('title' => NULL, 'description' => NULL, 'content' => NULL),
      'template' => 'nice-dash-dashboard-component',
      'file' => 'theme.inc',
      'path' => $path .'/theme',
    ),
    'nice_dash_page' => array(
      'arguments' => array('regions' => NULL),
      'template' => 'nice-dash-dashboard',
      'file' => 'theme.inc',
      'path' => $path .'/theme',
    ),
     'nice_dash_settings_form' => array(
      'arguments' => array('form' => NULL),
      'template' => 'nice-dash-dashboard-settings-form',
      'file' => 'theme.inc',
      'path' => $path .'/theme',
    ),
  );
}

/**
 * Implementation of hook_views_api().
 */
function nice_dash_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'nice_dash'),
  );
}

/**
 * Implementation of hook_block
 */
function nice_dash_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks['dashboard'] = array(
        'info' => t('Dashboard'),
        'admin' => TRUE,
        'cache' => BLOCK_CACHE_PER_ROLE,
        'weight' => -1,
      );
      return $blocks;
    case 'view': default:
      module_load_include('inc', 'nice_dash', 'nice_dash.blocks');
      switch ($delta) {
        case 'dashboard':
          $block['subject'] = t('Dashboard');
          $block['content'] = nice_dash_dashboard_block();
          break;
      }
      return $block;
  }
}