<?php

/**
 * Implementation of hook_menu
 */
function nice_dash_menu() {

 $items['admin/dashboard'] = array(
    'title' => 'Dashboard',
		'page callback' => 'nice_dash_dashboard_page',
		'access arguments' => array('view nice dashboard'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'nice_dash.pages.inc'
  );

 $items['admin/dashboard/view'] = array(
    'title' => 'View',
		'page callback' => 'nice_dash_dashboard_page',
		'access arguments' => array('view nice dashboard'),
		'type' => MENU_DEFAULT_LOCAL_TASK,
		'weight' => -1,
		'file' => 'nice_dash.pages.inc'
  );

  $items['admin/dashboard/settings'] = array(
    'title' => 'Settings',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('nice_dash_dashboard_settings_form'),
		'access arguments' => array('administer nice dashboard'),
		'type' => MENU_LOCAL_TASK,
		'file' => 'nice_dash.pages.inc'
  );

  return $items;
}

/**
  *  Implementation of hook_init().
  */
function nice_dash_init() {
  if (isset($_SESSION['admin_dashboard_redirect'])) {
    unset($_SESSION['admin_dashboard_redirect']);
    drupal_goto('admin/dashboard');
  }
}

/**
 * Implementation of hook_user
 */
function nice_dash_user($op, &$edit, &$account, $category = NULL){
  switch ($op) {
    case 'login':
	  if (user_access('view admindashboard')) {
	  	$_SESSION['admin_dashboard_redirect'] = true;
	  }
	  break;
  }
}

/**
 * Implementation of hook_perm
 */
function nice_dash_perm() {
  return array('administer nice dashboard','view nice dashboard');
}

/**
 * Implementation of hook_theme()
 */
function nice_dash_theme($existing, $type, $theme, $path){
  $path = drupal_get_path('module', 'nice_dash');

	return array(
    'nice_dash_component' => array(
      'arguments' => array('title' => NULL, 'description' => NULL, 'content' => NULL),
			'template' => 'nice-dash-dashboard-component',
      'file' => 'theme.inc',
      'path' => $path .'/theme',
    ),
		'nice_dash_page' => array(
			'arguments' => array('regions' => NULL),
			'template' => 'nice-dash-dashboard',
      'file' => 'theme.inc',
      'path' => $path .'/theme',
		),
		 'nice_dash_settings_form' => array(
      'arguments' => array('form' => NULL),
      'template' => 'nice-dash-dashboard-settings-form',
      'file' => 'theme.inc',
      'path' => $path .'/theme',
    ),
	);
}

/**
 * Implementation of hook_views_api().
 */
function nice_dash_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'nice_dash'),
  );
}

/**
 * Implementation of hook_block
 */
function nice_dash_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks['dashboard'] = array(
        'info' => t('Dashboard'),
        'admin' => TRUE,
        'cache' => FALSE,
				'weight' => -1,
      );
      return $blocks;
    case 'view': default:
			module_load_include('inc', 'nice_dash', 'nice_dash.blocks');
      switch ($delta) {
        case 'dashboard':
          $block['subject'] = t('Dashboard');
          $block['content'] = nice_dash_dashboard_block();
          break;
      }
      return $block;
  }
}

/**
 * Dashboard regions
 *
 * @return: An array of layout regions available for widgets
 */
function nice_dash_regions() {
  return array(
		'header' => t('Header'),
		'left' => t('Left'),
		'right' => t('Right'),
		'footer' => t('Footer'),
		'disabled' => t('Disabled')
  );
}

/**
 * Fetch widget values
 */
function nice_dash_widget_values($key){
 //
 $result = db_query("SELECT region, weight FROM {nice_dash_widget_values} WHERE widget_key = '%s'", $key);
 while($row = db_fetch_array($result)){
   return $row;
 }
 // If empty
 return nice_dash_widget_default_values();
}

/**
 * Default widget values
 */
function nice_dash_widget_default_values(){
 return array(
   'weight' => 0,
   'region' => 'disabled'
 );
}