<?php

/**
 * Implementation of hook_views_api().
 */
function nice_dash_system_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'nice_dash_system'),
  );
}

/**
 * Implementation of hook_nice_dash_widgets()
 */
function nice_dash_system_nice_dash_widgets(){
	module_load_include('inc', 'nice_dash_system', 'nice_dash_system.widgets');

	/*$widgets['system_dblog'] = array(
		'title' => t('Latest log entries'),
		'callback' => 'nice_dash_system_widget_dblog',
		//'file' => 'nice_dash_content.widgets.inc'
	);*/

	return $widgets;
}