<?php

/**
 * Implementation of hook_views_api().
 */
function nice_dash_dblog_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'nice_dash_dblog'),
  );
}

/**
 * Implementation of hook_nice_dash_widgets()
 */
function nice_dash_dblog_nice_dash_widgets(){
	module_load_include('inc', 'nice_dash_dblog', 'nice_dash_dblog.widgets');

	$widgets['system_dblog'] = array(
		'title' => t('Latest log entries'),
		'callback' => 'nice_dash_dblog_widget_dblog',
		//'file' => 'nice_dash_content.widgets.inc'
	);

	return $widgets;
}