<?php


/**
 * Implementation of hook_menu
 */
function nice_dash_content_menu() {


  /*$items['admin/dashboard/view'] = array(
    'title' => t('Dashboard'),
		'page callback' => 'nice_dash_dashboard_page',
		'access arguments' => array('view admindashboard'),
		'type' => MENU_CALLBACK,
  );

  $items['admin/dashboard/list'] = array(
		'page callback' => 'nice_dash_dashboard_list',
		'callback arguments' => array('item', 1),
		'access arguments' => array('view admindashboard'),
		'type' => MENU_CALLBACK,
  );

  $items['admin/dashboard/demote/%'] = array(
		'page callback' => 'nice_dash_dashboard_demote',
		'page arguments' => array(3),
		'access arguments' => array('view admindashboard'),
		'file' => 'nice_dash.pages.inc',
		'type' => MENU_CALLBACK,
  );

  $items['admin/dashboard/unsticky/%'] = array(
		'page callback' => 'nice_dash_dashboard_unsticky',
		'page arguments' => array(3),
		'access arguments' => array('view admindashboard'),
		'type' => MENU_CALLBACK,
  );

  return $items;*/
}

/**
 * Implementation of hook_views_api().
 */
function nice_dash_content_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'nice_dash_content'),
  );
}

/**
 * Implementation of hook_nice_dash_widgets()
 */
function nice_dash_content_nice_dash_widgets(){
	module_load_include('inc', 'nice_dash_content', 'nice_dash_content.widgets');


	$widgets['content_add'] = array(
		'title' => t('Add content'),
		'callback' => 'nice_dash_content_widget_add_content',
		//'file' => 'nice_dash_content.widgets.inc'
	);

	$widgets['content_latest'] = array(
		'title' => t('Latest content'),
		'callback' => 'nice_dash_content_widget_latest_content',
		//'file' => 'nice_dash_content.widgets.inc'
	);
	$widgets['content_sticky'] = array(
		'title' => t('Sticky content'),
		'callback' => 'nice_dash_content_widget_sticky',
		//'file' => 'nice_dash_content.widgets.inc'
	);
	$widgets['content_promoted'] = array(
		'title' => t('Promoted content'),
		'callback' => 'nice_dash_content_widget_promoted',
		//'file' => 'nice_dash_content.widgets.inc'
	);

	return $widgets;
}