<?php

/**
 * Implementation of hook_views_api().
 */
function nice_dash_comments_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'nice_dash_comments'),
  );
}

/**
 * Implementation of hook_nice_dash_widgets()
 */
function nice_dash_comments_nice_dash_widgets(){
	module_load_include('inc', 'nice_dash_comments', 'nice_dash_comments.widgets');


	$widgets['latest_comments'] = array(
		'title' => t('Latest comments'),
		'callback' => 'nice_dash_comments_widget_latest_comments',
		//'file' => 'nice_dash_content.widgets.inc'
	);

	return $widgets;
}