<?php

/**
 * Implementation of hook_views_api().
 */
function nice_dash_scheduler_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'nice_dash_scheduler'),
  );
}

/**
 * Implementation of hook_nice_dash_widgets()
 */
function nice_dash_scheduler_nice_dash_widgets(){
	module_load_include('inc', 'nice_dash_scheduler', 'nice_dash_scheduler.widgets');

	$widgets['scheduler_unpublish'] = array(
		'title' => t('Content to be unpublished'),
		'callback' => 'nice_dash_scheduler_widget_unpublish',
		//'file' => 'nice_dash_content.widgets.inc'
	);
  $widgets['scheduler_publish'] = array(
		'title' => t('Content to be published'),
		'callback' => 'nice_dash_scheduler_widget_publish',
		//'file' => 'nice_dash_content.widgets.inc'
	);


	return $widgets;
}